 <dependencies>
 
     <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
 
    <dependency>
      <groupId>org.glassfish.jersey.core</groupId>
      <artifactId>jersey-client</artifactId>
      <version>2.22.1</version>
      <scope>provided</scope>
    </dependency>
 
    <dependency>
   	  <groupId>org.glassfish.jersey.media</groupId>
   	  <artifactId>jersey-media-json-jackson</artifactId>
   	  <version>2.22.1</version>
    </dependency>
        <dependency>
            <groupId>unknown.binary</groupId>
            <artifactId>AbsoluteLayout</artifactId>
            <version>SNAPSHOT</version>
        </dependency>
    </dependencies>
